### ISSUE TITLE
Why is `MiscExtensions` an extension on `String?` and not on `String`

### ISSUE THREAD

**Issue by abrahammurciano** [esentis/string_extensions#45]
Not so much a feature request, more a design question to satisfy my curiosity. If something can be done about it, all the better!

This code gives an error that "A value of type 'String?' can't be assigned to a variable of type 'String'". IMHO this should be the ideal way to use the extension properties.
```dart
String foo = "foo".capitalize;
```

Instead we are forced to use a `!` if we know the initial string to not be null.
```dart
String foo = "foo".capitalize!;
```

I understand that the advantage of the current approach is so we can easily work with nullable strings like this.
```dart
String? bar = maybe ? "not-null" : null;
String? biz = bar.capitalize;
```

However it seems more appropriate to force the usage of the `?` operator where things might be null instead of forcing the `!` operator where we know they aren't null, like so.
```dart
String foo = "foo".capitalize; // Should be good
String? biz = bar?.capitalize; // Should be good. Forcing ? is appropriate since bar may be null

String foo = "foo".capitalize!; // Should be bad. "foo" is known to not be null, so .capitalize should be the same
String? biz = bar.capitalize; // Should be bad. bar may be null so it shouldn't have a .capitalize property. use ?.capitalize instead
```

I know changing it would break backwards compatibility, so I'm not requesting it be changed, but if I'm missing something and the current approach was chosen for some other benefit I'm not aware of, I'd love to learn what that is (I'm kind of new to dart and exploring its mechanisms). Maybe there can be two extension classes, one on `String` and the other on `String?` to keep backwards compatibility? (The latter could easily be implemented in terms of the former, though importing both may cause name collisions)

**Comment by esentis** [comment]
Hello there @abrahammurciano !

Thanks for your message and the valid points you raised. This is something I've been thinking it aswell and since I see other users have similar issue, I've decided to extend the library to include both `String` and `String?`. This way, you'll have the flexibility to use .capitalize directly on non-nullable strings without needing the `!` operator, while still handling nullable strings gracefully and of course not breaking current projects.

I've also considered the potential impact on the size of the library. Fortunately, thanks to Dart's tree shaking and the minimal nature of the changes, the increase in size should be negligible.

Appreciate your input, and stay tuned for the update!
